### ISSUE TITLE
Need to differentiate between standard multiqc (30X coverage) and WES multiqc (20X)

### ISSUE THREAD

**Issue by aledj2** [moka-guys/dnanexus_multiqc#1]

**Comment by aledj2** [comment]
could be as simple as packaging both up and cd'ing and installing based on presence/absence of WES in filename

**Comment by aledj2** [comment]
could also clone directly from wook's github using multiple branches? or is there a setting in the YAML?

**Comment by woook** [comment]
It's not a setting in the YAML but small change to HsMetrics.py
See https://github.com/woook/MultiQC/commit/482640208e0b882b71c45dc01d4cb30a249f72ed

**Comment by aledj2** [comment]
I assume that changes more than just the header!?

**Comment by woook** [comment]
It's the HsMetrics.py in MultiQC, tells MultiQC to take the 30X value...

Anyway, MultiQC had now implemented coverage threshold as a configurable in the YAML (I think I raised an issue...).

See below from MultiQC docs:

Coverage Levels

It's possible to customise the HsMetrics "Target Bases 30X" coverage and WgsMetrics "Fraction of Bases over 30X" that are shown in the general statistics table. This must correspond to field names in the picard report, such as PCT_TARGET_BASES_2X / PCT_10X. Any numbers not found in the reports will be ignored.

The coverage levels available for HsMetrics are typically 1, 2, 10, 20, 30, 40, 50 and 100X.

The coverage levels available for WgsMetrics are typically 1, 5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 90 and 100X.

To customise this, add the following to your MultiQC config:

```picard_config:
    general_stats_target_coverage:
        - 10
        - 50```

http://multiqc.info/docs/#picard

**Comment by aledj2** [comment]
For some reason code from https://github.com/ewels/MultiQC doesn't work.
