### ISSUE TITLE
multiqc app fails due to networkx version error

### ISSUE THREAD

**Issue by NMNS93** [moka-guys/dnanexus_multiqc#17]
Yesterday the multiqc app failed to run on DNA Nexus (fork at moka-guys/multiqc was updated).

**job-F9FkKgj08bGvF07XPbV92zgZ**:
```    error: networkx 1.11 is installed but networkx==2.0 is required by set(['spectra'])   ```

The app installs conda and a list of dependencies:
`conda install jinja2 click markupsafe simplejson freetype networkx=1.11 -y`
The networkx version is made explicit here because of a [previous issue](https://github.com/moka-guys/dnanexus_multiqc/issues/8)

I tried rebuilding the app with the following changes (**applet-F9FpfX008bGX1vv1JZ3Qzyz4**):
`conda update conda` # required to allow newer networkx versions to show up in conda package lists
`conda install jinja2 click markupsafe simplejson freetype networkx=2.0 -y`

The app gets further through the dependency installations but throws the same networkx=1.11 error. I think another dependency might overwrite the networkx version that will be installed. See:

**job-F9Fpff808bGv80vb68Jy3zXk**:
```    
    The following NEW packages will be INSTALLED:
    .....
    networkx:   2.0-py27hfc23926_0 
    .....
    Installed /home/dnanexus/Miniconda/lib/python2.7/site-packages/colormath-3.0.0-py2.7.egg
    error: networkx 1.11 is installed but networkx==2.0 is required by set(['spectra'])
```
Relevant recent update to spectra dependencies : https://github.com/jsvine/spectra/issues/8
Will try adding `spectra=0.0.9`

**Comment by aledj2** [comment]
fixed
