### ISSUE TITLE
Would it be better to have 20x/30x as an input option?

### ISSUE THREAD

**Issue by andyb3** [moka-guys/dnanexus_multiqc#22]
Currently app is hardcoded to look for Pan493 in the filename and switch to 20x if it is found. However when doing WES reanalysis on older cases, some of them don't have Pan493 in filename.

**Comment by aledj2** [comment]
Add coverage level as an input. Then can have one config.yaml and append the below to config file:
 picard_config:
    general_stats_target_coverage:
        - $coverage_level

**Comment by NMNS93** [comment]
Added to latest release
